### HOW TO RUN: (!!! do not forget to change mapped LOCAL_DIR for Windows/Linux)
# docker build -t jupyter_image -f ./Dockerfile_jupyter ./
# docker run --name jupnot --restart=always -e GRANT_SUDO=yes --user root -p 8888:8888 -d -v /LOCAL_DIR:/home/jovyan jupyter_image start-notebook.sh --NotebookApp.token=''
# open in browser: 0.0.0.0:8888/lab

############################
FROM jupyter/datascience-notebook:latest
MAINTAINER me
USER root

# Update
RUN 	apt-get update -qq && apt-get upgrade -y
RUN 	echo 'export TERM=xterm' >> ~/.bashrc

# Install BASE tools
RUN 	apt-get install -y nano tree man wget htop tldr jq

RUN    	apt-get install --no-install-recommends -y openjdk-8-jre-headless ca-certificates-java && \
    	rm -rf /var/lib/apt/lists/*

# Install DEV tools
RUN 	pip install --upgrade pip \
		# SSH
		sshtunnel paramiko \
		# DB connectors
		#libpq-dev psycopg2 \
		redis clickhouse-sqlalchemy pandas-datareader \
		# Google BigQuery
		google-api-python-client google-auth-httplib2 google-auth-oauthlib pandas_gbq \
		# pd.to_parquet
		fastparquet pyarrow \
		# https://github.com/krassowski/jupyterlab-lsp
		jupyter-lsp python-language-server[all] black \
		# other
		boto3 aiohttp bs4 click pytest

# hotfix versions
RUN 	pip install --upgrade google-cloud-bigquery==1.22.0

# Install JupLab extensions
#RUN 	pip install beakerx && pip install py4j && beakerx install # install beakerx

RUN 	jupyter labextension install @jupyterlab/toc --no-build \
	&& 	jupyter labextension install @krassowski/jupyterlab_go_to_definition --no-build \
	&&	jupyter labextension install @krassowski/jupyterlab-lsp --no-build \
	&&	jupyter labextension install @jupyterlab/debugger --no-build \ 
	#&&	jupyter labextension install beakerx-jupyterlab --no-build \
	&& 	jupyter lab build

### CLEAN
RUN     apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
